Milestone 1 - Mobile Screen size for Portfolio's Navbar & Headline Sections
chelmerrox/2-my-portfolio pull request #1
Opened 2022-03-18 22:15 UTC by chelmerrox

I need a review for this project. I've chosen template 5 from Figma as my design guide. I have completed it & its requirements to:

1. create the navbar (section 1) ; navbar
2. create the headline (section 2); headline
  a. headline-section-1 has the following:
    - name (using h1)
    - my-info for the paragraph under the name
    - start-collab-btn for the Start Collaboration button
   b. headline-section-2 has the following:
   - the hero image/geometric-img-headline 
- used display: flex; property where it can be applied
- stuck to the design, typography etc from template 5 in Figma

Thanks in advance for your review, comments & help!

2022-03-18 23:58 UTC, Mre55 requested changes
**Hi @chelmerrox,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commits messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 
_Check the comments under the review. 👇 _

<img width="430" src="https://media1.giphy.com/media/7JsChhLbpj0rJtzimC/giphy.gif"/>

## Optional suggestions 🔴
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

-N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 23:58 UTC, Mre55 commented on my-portfolio.html
> +    </nav>
Nice use of `nav` tag 👍 but let's wrap this `nav` tag inside the `header` tag. Since the toolbar is our header it'll make our code clean and readable also it's good practice to use proper HTML semantic tags.

2022-03-18 23:58 UTC, Mre55 commented on my-portfolio.html
> +      <img src="images/image1.jpg" alt="A geometric art on the top left corner" class="geometric-img-nav"/>
Please use this image as a `background-image` inside the .css file. Since it's a decoration and decorations are always background images, not `img` tags.

2022-03-18 23:58 UTC, Mre55 commented on my-portfolio.html
> +        <img src="images/image2.jpg" alt="A colorful geometric art" class="geometric-img-headline"/>
Also, this image should also have to be `background-image` as mentioned above. Kindly move this to the .css file and use it as described above.

2022-03-19 03:58 UTC, nicupop729 requested changes
# STATUS: Required Changes ♻️

Hi @chelmerrox , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![](https://media.giphy.com/media/iZKF7CKpEEva2OZE6a/giphy.gif)

### Required Changes ♻️

- [ ] _Check the comments under the review._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 03:58 UTC, nicupop729 commented on styles/my-portfolio.css
> +  left: 284px;
- [ ] Please remove this fixed positioning as we want to make our design responsive. Instead, place your elements on your UI using flexbox, or in this case, maybe float.

2022-03-19 03:58 UTC, nicupop729 commented on styles/my-portfolio.css
> +  width: 220px;
- [ ] Please remove this fixed-width as we want to make our design responsive. After removing the fixed width, take the all necessary measures to still match the figma design.

2022-03-19 03:58 UTC, nicupop729 commented on styles/my-portfolio.css
> +  width: 288px;
Same here, please remove the fixed-width applied to your elements.

2022-03-19 03:58 UTC, nicupop729 commented on styles/my-portfolio.css
> +}
The background image for this milestone is not displayed on the UI.

- [ ] Please take action to address this issue, as we want that our design to match as close as possible the figma template.

Your design:
![image](https://user-images.githubusercontent.com/83596135/159105693-bb374a16-fd65-4300-b8fe-7f988604e49e.png)

2022-03-19 14:04 UTC, MeqdamAlqudah approved these changes
# Hi @chelmerrox , 

### Status: Approved ✔️

:+1:  You have implemented all the suggested changes made by the previous reviewer. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**_Check the comments under the review_**


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Dipesh Kumar_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 14:04 UTC, MeqdamAlqudah commented on my-portfolio.html
> +        </section>
- [ OPTIONAL] Please the button should follow the button styling: Active, Hover, and Pressed 
![image](https://user-images.githubusercontent.com/74744787/159124135-5c8a386c-2ea5-40f3-a4b7-2e908996733e.png)

2022-03-19 14:40 UTC, merged